# Generated by Django 4.0.1 on 2022-01-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.TextField(default='Default Title'),
            preserve_default=False,
        ),
    ]
