# Generated by Django 4.0.1 on 2022-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.TextField(default='No Author Available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
